# Generated by Django 4.2.3 on 2023-08-08 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="Product",
            new_name="product",
        ),
    ]
